### ISSUE TITLE
Errors Trying to Run PyCut.py

### ISSUE THREAD

**Issue by adf5051** [tcreeds/PyCut#1]
There are failed to start errors when trying to start the .xo file.

When trying to run PyCut.py on the XO we get this stack trace error.

[olpc@acd41290453237683619 PyCut]$ python PyCut.py
Traceback (most recent call last):
  File "PyCut.py", line 3, in <module>
    from game import PyCutGame as PyCut
  File "/PyCut/game/__init__.py", line 3, in <module>
    from . import scenes, events, objects
  File "/PyCut/game/scenes/__init__.py", line 2, in <module>
    from .help_scene import HelpScene
  File "/PyCut/game/scenes/help_scene.py", line 3, in <module>
    from game.objects import Text, Button, STATE
  File "/PyCut/game/objects/__init__.py", line 1, in <module>
    from enum import Enum
ImportError: No module named enum

**Comment by tcreeds** [comment]
enum is the only dependency for this project, and it really isn't necessary in the code. I removed the reference to enum and changed the code that required it. If you install the package (pip install enum34) the program runs, but if you use this fork it should work fine.
